In [ ]:
# -*- coding: utf-8 -*-
"""
Clase de Exploración, Limpieza, Formateo y Consultas en Pandas con Datos de Jugadores de Fútbol

Este notebook cubre los siguientes temas:
1. Carga del dataset y exploración inicial.
2. Limpieza de datos: manejo de valores faltantes, duplicados, etc.
3. Formateo de datos: cambio de tipos de datos, creación de nuevas columnas, etc.
4. Consultas en Pandas: filtrado básico, avanzado y con funciones.
5. Ejercicios prácticos.

Dataset utilizado: Football Players Data (disponible en Kaggle: https://www.kaggle.com/datasets/maso0dahmed/football-players-data/data)
"""

import pandas as pd
import numpy as np

# ------------------------------------------------------------------------------
# 1. Carga del Dataset y Exploración Inicial
# ------------------------------------------------------------------------------

print("# 1. Carga del Dataset y Exploración Inicial")

# Cargar el dataset desde la URL
url = "https://raw.githubusercontent.com/juansanmiguel/pandas_para_data_science/main/datasets/football_players.csv"
try:
    #Actualizar la ruta o path
    df = pd.read_csv('/home/ravi/Documents/Kevin/projects/data/fifa_players.csv')
    print("\nDataset cargado exitosamente.")
except Exception as e:
    print(f"\nError al cargar el dataset: {e}")
    raise
#Manejo de excepciones

# 1. Carga del Dataset y Exploración Inicial

Dataset cargado exitosamente.

In [2]:
# Primer vistazo al dataset
print("\nPrimeras 5 filas del dataset:")
print(df.head())

print("\nInformación general del dataset:")
df.info()

print("\Estadísticas descriptivas de las columnas numéricas:")
print(df.describe())

print("\nNúmero de valores únicos por columna:")
print(df.nunique())
#nunique te cuenta las categorias de cada columna

Primeras 5 filas del dataset:
           name                       full_name birth_date  age  height_cm  \
0      L. Messi  Lionel Andrés Messi Cuccittini  6/24/1987   31     170.18
1    C. Eriksen    Christian  Dannemann Eriksen  2/14/1992   27     154.94
2      P. Pogba                      Paul Pogba  3/15/1993   25     190.50
3    L. Insigne                 Lorenzo Insigne   6/4/1991   27     162.56
4  K. Koulibaly               Kalidou Koulibaly  6/20/1991   27     187.96

   weight_kgs  positions nationality  overall_rating  potential  ...  \
0        72.1   CF,RW,ST   Argentina              94         94  ...
1        76.2  CAM,RM,CM     Denmark              88         89  ...
2        83.9     CM,CAM      France              88         91  ...
3        59.0      LW,ST       Italy              88         88  ...
4        88.9         CB     Senegal              88         91  ...

   long_shots  aggression interceptions  positioning  vision  penalties  \
0          94          48            22           94      94         75
1          89          46            56           84      91         67
2          82          78            64           82      88         82
3          84          34            26           83      87         61
4          15          87            88           24      49         33

  composure  marking standing_tackle  sliding_tackle
0        96       33              28              26
1        88       59              57              22
2        87       63              67              67
3        83       51              24              22
4        80       91              88              87

[5 rows x 51 columns]

Información general del dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17954 entries, 0 to 17953
Data columns (total 51 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   name                           17954 non-null  object
 1   full_name                      17954 non-null  object
 2   birth_date                     17954 non-null  object
 3   age                            17954 non-null  int64
 4   height_cm                      17954 non-null  float64
 5   weight_kgs                     17954 non-null  float64
 6   positions                      17954 non-null  object
 7   nationality                    17954 non-null  object
 8   overall_rating                 17954 non-null  int64
 9   potential                      17954 non-null  int64
 10  value_euro                     17699 non-null  float64
 11  wage_euro                      17708 non-null  float64
 12  preferred_foot                 17954 non-null  object
 13  international_reputation(1-5)  17954 non-null  int64
 14  weak_foot(1-5)                 17954 non-null  int64
 15  skill_moves(1-5)               17954 non-null  int64
 16  body_type                      17954 non-null  object
 17  release_clause_euro            16117 non-null  float64
 18  national_team                  857 non-null    object
 19  national_rating                857 non-null    float64
 20  national_team_position         857 non-null    object
 21  national_jersey_number         857 non-null    float64
 22  crossing                       17954 non-null  int64
 23  finishing                      17954 non-null  int64
 24  heading_accuracy               17954 non-null  int64
 25  short_passing                  17954 non-null  int64
 26  volleys                        17954 non-null  int64
 27  dribbling                      17954 non-null  int64
 28  curve                          17954 non-null  int64
 29  freekick_accuracy              17954 non-null  int64
 30  long_passing                   17954 non-null  int64
 31  ball_control                   17954 non-null  int64
 32  acceleration                   17954 non-null  int64
 33  sprint_speed                   17954 non-null  int64
 34  agility                        17954 non-null  int64
 35  reactions                      17954 non-null  int64
 36  balance                        17954 non-null  int64
 37  shot_power                     17954 non-null  int64
 38  jumping                        17954 non-null  int64
 39  stamina                        17954 non-null  int64
 40  strength                       17954 non-null  int64
 41  long_shots                     17954 non-null  int64
 42  aggression                     17954 non-null  int64
 43  interceptions                  17954 non-null  int64
 44  positioning                    17954 non-null  int64
 45  vision                         17954 non-null  int64
 46  penalties                      17954 non-null  int64
 47  composure                      17954 non-null  int64
 48  marking                        17954 non-null  int64
 49  standing_tackle                17954 non-null  int64
 50  sliding_tackle                 17954 non-null  int64
dtypes: float64(7), int64(35), object(9)
memory usage: 7.0+ MB
\Estadísticas descriptivas de las columnas numéricas:
                age     height_cm    weight_kgs  overall_rating     potential  \
count  17954.000000  17954.000000  17954.000000    17954.000000  17954.000000
mean      25.565445    174.946921     75.301047       66.240169     71.430935
std        4.705708     14.029449      7.083684        6.963730      6.131339
min       17.000000    152.400000     49.900000       47.000000     48.000000
25%       22.000000    154.940000     69.900000       62.000000     67.000000
50%       25.000000    175.260000     74.800000       66.000000     71.000000
75%       29.000000    185.420000     79.800000       71.000000     75.000000
max       46.000000    205.740000    110.200000       94.000000     95.000000

         value_euro      wage_euro  international_reputation(1-5)  \
count  1.769900e+04   17708.000000                   17954.000000
mean   2.479280e+06    9902.134628                       1.111674
std    5.687014e+06   21995.593750                       0.392168
min    1.000000e+04    1000.000000                       1.000000
25%    3.250000e+05    1000.000000                       1.000000
50%    7.000000e+05    3000.000000                       1.000000
75%    2.100000e+06    9000.000000                       1.000000
max    1.105000e+08  565000.000000                       5.000000

       weak_foot(1-5)  skill_moves(1-5)  ...    long_shots    aggression  \
count    17954.000000      17954.000000  ...  17954.000000  17954.000000
mean         2.945695          2.361034  ...     46.852456     55.816531
std          0.663691          0.763223  ...     19.429337     17.394047
min          1.000000          1.000000  ...      3.000000     11.000000
25%          3.000000          2.000000  ...     32.000000     44.000000
50%          3.000000          2.000000  ...     51.000000     59.000000
75%          3.000000          3.000000  ...     62.000000     69.000000
max          5.000000          5.000000  ...     94.000000     95.000000

       interceptions   positioning        vision     penalties     composure  \
count   17954.000000  17954.000000  17954.000000  17954.000000  17954.000000
mean       46.657959     49.857302     53.406260     48.357302     58.680183
std        20.754649     19.694311     14.156038     15.810844     11.625541
min         3.000000      2.000000     10.000000      5.000000     12.000000
25%        26.000000     38.000000     44.000000     38.000000     51.000000
50%        52.000000     55.000000     55.000000     49.000000     60.000000
75%        64.000000     64.000000     64.000000     60.000000     67.000000
max        92.000000     95.000000     94.000000     92.000000     96.000000

            marking  standing_tackle  sliding_tackle
count  17954.000000     17954.000000    17954.000000
mean      47.162861        47.733040       45.705915
std       20.037346        21.674973       21.285812
min        3.000000         2.000000        3.000000
25%       30.000000        27.000000       24.000000
50%       52.500000        55.000000       52.000000
75%       64.000000        66.000000       64.000000
max       94.000000        93.000000       90.000000

[8 rows x 42 columns]

Número de valores únicos por columna:
name                             16995
full_name                        17898
birth_date                        6156
age                                 29
height_cm                           20
weight_kgs                          57
positions                          890
nationality                        160
overall_rating                      47
potential                           47
value_euro                         211
wage_euro                          138
preferred_foot                       2
international_reputation(1-5)        5
weak_foot(1-5)                       5
skill_moves(1-5)                     5
body_type                           10
release_clause_euro               1248
national_team                      103
national_rating                     22
national_team_position              29
national_jersey_number              38
crossing                            89
finishing                           94
heading_accuracy                    91
short_passing                       85
volleys                             88
dribbling                           94
curve                               89
freekick_accuracy                   92
long_passing                        84
ball_control                        90
acceleration                        86
sprint_speed                        85
agility                             82
reactions                           68
balance                             81
shot_power                          91
jumping                             74
stamina                             86
strength                            74
long_shots                          92
aggression                          85
interceptions                       88
positioning                         94
vision                              85
penalties                           87
composure                           83
marking                             91
standing_tackle                     89
sliding_tackle                      87
dtype: int64

In [3]:
# ------------------------------------------------------------------------------
# 2. Limpieza de Datos
# ------------------------------------------------------------------------------

print("\n# 2. Limpieza de Datos")

# Identificar valores faltantes
print("\nValores faltantes por columna:")
print(df.isnull().sum().sort_values(ascending=False))

# 2. Limpieza de Datos

Valores faltantes por columna:
national_jersey_number           17097
national_team_position           17097
national_rating                  17097
national_team                    17097
release_clause_euro               1837
value_euro                         255
wage_euro                          246
name                                 0
shot_power                           0
ball_control                         0
acceleration                         0
sprint_speed                         0
agility                              0
reactions                            0
balance                              0
stamina                              0
jumping                              0
freekick_accuracy                    0
strength                             0
long_shots                           0
aggression                           0
interceptions                        0
positioning                          0
vision                               0
penalties                            0
composure                            0
marking                              0
standing_tackle                      0
long_passing                         0
short_passing                        0
curve                                0
preferred_foot                       0
birth_date                           0
age                                  0
height_cm                            0
weight_kgs                           0
positions                            0
nationality                          0
overall_rating                       0
potential                            0
international_reputation(1-5)        0
dribbling                            0
weak_foot(1-5)                       0
skill_moves(1-5)                     0
body_type                            0
crossing                             0
finishing                            0
heading_accuracy                     0
full_name                            0
volleys                              0
sliding_tackle                       0
dtype: int64

In [4]:
len(df.columns)
threshold = 5
len(df.columns) - threshold

46

In [5]:
df.shape

(17954, 51)

In [6]:
# Estrategias para manejar valores faltantes (ejemplos)

# a) Eliminar filas con muchos valores faltantes (umbral arbitrario)
threshold = 5
df_cleaned = df.dropna()
df_cleaned = df.dropna(thresh=len(df.columns) - threshold)
print(f"\nDataset después de eliminar filas con más de {threshold} valores faltantes: {len(df_cleaned)} filas.")
#para meter variables en una cadena de texto se coloca la f y luego la variable entre llaves

Dataset después de eliminar filas con más de 5 valores faltantes: 17699 filas.

In [7]:
#release_clause_euro value_euro wage_euro   


# b) Imputar valores faltantes en columnas específicas (ejemplos)
# Imputar la edad con la mediana
median = df_cleaned['release_clause_euro'].median()
df_cleaned['release_clause_euro'].fillna(median, inplace=True)
print("\nValores faltantes en 'release_clause_euro' después de la imputación:", df_cleaned['release_clause_euro'].isnull().sum())

# Imputar la altura con la media
mean = df_cleaned['value_euro'].mean()
df_cleaned['value_euro'].fillna(mean, inplace=True)
print("Valores faltantes en 'value_euro' después de la imputación:", df_cleaned['value_euro'].isnull().sum())

# Imputar la columna 'Weight' con la moda
mode = df_cleaned['wage_euro'].mode()[0]
df_cleaned['wage_euro'].fillna(mode, inplace=True)
print("Valores faltantes en 'wage_euro' después de la imputación:", df_cleaned['wage_euro'].isnull().sum())

Valores faltantes en 'release_clause_euro' después de la imputación: 0
Valores faltantes en 'value_euro' después de la imputación: 0
Valores faltantes en 'wage_euro' después de la imputación: 0

/tmp/ipykernel_11614/4227980213.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['release_clause_euro'].fillna(median, inplace=True)
/tmp/ipykernel_11614/4227980213.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['value_euro'].fillna(mean, inplace=True)
/tmp/ipykernel_11614/4227980213.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['wage_euro'].fillna(mode, inplace=True)

In [8]:

# c) Manejo de duplicados
print("\nNúmero de filas duplicadas:", df_cleaned.duplicated().sum())

#Siempre debo agotar las opciones antes de borrar
# Eliminar filas duplicadas
df_cleaned.drop_duplicates(inplace=True)
print("Número de filas después de eliminar duplicados:", len(df_cleaned))

Número de filas duplicadas: 0
Número de filas después de eliminar duplicados: 17699

/tmp/ipykernel_11614/287793177.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned.drop_duplicates(inplace=True)

In [9]:
# ------------------------------------------------------------------------------
# 3. Formateo de Datos
# ------------------------------------------------------------------------------

print("\n# 3. Formateo de Datos")

# a) Cambiar tipos de datos
print("\nTipo de dato de la columna 'Height' antes:", df_cleaned['Height'].dtype)
df_cleaned['Height'] = pd.to_numeric(df_cleaned['Height'], errors='coerce')
print("Tipo de dato de la columna 'Height' después:", df_cleaned['Height'].dtype)
print("\nTipo de dato de la columna 'Weight' antes:", df_cleaned['Weight'].dtype)
df_cleaned['Weight'] = pd.to_numeric(df_cleaned['Weight'], errors='coerce')
print("Tipo de dato de la columna 'Weight' después:", df_cleaned['Weight'].dtype)

# 3. Formateo de Datos

KeyError: 'Height'

In [10]:
#Para practicar vamos a cambiar todas las columnas a texto
df_text = df_cleaned.astype(str)

In [11]:
df_text['age']=pd.to_numeric(df_text['age'], errors='coerce')#to_numeric detecta automaticamente el tipo
df_text['age']=df_text['age'].astype(int)#astype tienes que especificar el tipo
df_text['age']=df_text['age'].astype(float)

In [12]:
#Tarea: Pasar al formato correcto cada columna

In [13]:
df_cleaned.height_cm

0        170.18
1        154.94
2        190.50
3        162.56
4        187.96
          ...
17949    175.26
17950    182.88
17951    185.42
17952    175.26
17953    190.50
Name: height_cm, Length: 17699, dtype: float64

In [14]:
df_cleaned.weight_kgs

0        72.1
1        76.2
2        83.9
3        59.0
4        88.9
         ...
17949    74.8
17950    79.8
17951    89.8
17952    64.9
17953    79.8
Name: weight_kgs, Length: 17699, dtype: float64

In [15]:
#para generar salidas mas limpias
import warnings
warnings.filterwarnings('ignore')

In [16]:
# b) Crear nuevas columnas (ejemplos)

# Calcular el Índice de Masa Corporal (IMC)
# IMC = peso (kg) / altura (m)^2 (elevado al cuadrado)
# Asumiendo que 'Height' está en cm, lo convertimos a metros
df_cleaned['height_m'] = (df_cleaned['height_cm'] / 100).round(2)
df_cleaned['BMI'] = df_cleaned['weight_kgs'] / (df_cleaned['height_m'] ** 2)

In [17]:


print("\nPrimeras filas con la columna 'BMI':")
print(df_cleaned[['Name', 'Height', 'Weight', 'BMI']].head())

# Crear una columna con la inicial del nombre
df_cleaned['Initial'] = df_cleaned['Name'].str[0]
print("\nPrimeras filas con la columna 'Initial':")
print(df_cleaned[['Name', 'Initial']].head())

Primeras filas con la columna 'BMI':

KeyError: "['Name', 'Height', 'Weight'] not in index"

In [18]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17699 entries, 0 to 17953
Data columns (total 53 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   name                           17699 non-null  object
 1   full_name                      17699 non-null  object
 2   birth_date                     17699 non-null  object
 3   age                            17699 non-null  int64
 4   height_cm                      17699 non-null  float64
 5   weight_kgs                     17699 non-null  float64
 6   positions                      17699 non-null  object
 7   nationality                    17699 non-null  object
 8   overall_rating                 17699 non-null  int64
 9   potential                      17699 non-null  int64
 10  value_euro                     17699 non-null  float64
 11  wage_euro                      17699 non-null  float64
 12  preferred_foot                 17699 non-null  object
 13  international_reputation(1-5)  17699 non-null  int64
 14  weak_foot(1-5)                 17699 non-null  int64
 15  skill_moves(1-5)               17699 non-null  int64
 16  body_type                      17699 non-null  object
 17  release_clause_euro            17699 non-null  float64
 18  national_team                  857 non-null    object
 19  national_rating                857 non-null    float64
 20  national_team_position         857 non-null    object
 21  national_jersey_number         857 non-null    float64
 22  crossing                       17699 non-null  int64
 23  finishing                      17699 non-null  int64
 24  heading_accuracy               17699 non-null  int64
 25  short_passing                  17699 non-null  int64
 26  volleys                        17699 non-null  int64
 27  dribbling                      17699 non-null  int64
 28  curve                          17699 non-null  int64
 29  freekick_accuracy              17699 non-null  int64
 30  long_passing                   17699 non-null  int64
 31  ball_control                   17699 non-null  int64
 32  acceleration                   17699 non-null  int64
 33  sprint_speed                   17699 non-null  int64
 34  agility                        17699 non-null  int64
 35  reactions                      17699 non-null  int64
 36  balance                        17699 non-null  int64
 37  shot_power                     17699 non-null  int64
 38  jumping                        17699 non-null  int64
 39  stamina                        17699 non-null  int64
 40  strength                       17699 non-null  int64
 41  long_shots                     17699 non-null  int64
 42  aggression                     17699 non-null  int64
 43  interceptions                  17699 non-null  int64
 44  positioning                    17699 non-null  int64
 45  vision                         17699 non-null  int64
 46  penalties                      17699 non-null  int64
 47  composure                      17699 non-null  int64
 48  marking                        17699 non-null  int64
 49  standing_tackle                17699 non-null  int64
 50  sliding_tackle                 17699 non-null  int64
 51  height_m                       17699 non-null  float64
 52  BMI                            17699 non-null  float64
dtypes: float64(9), int64(35), object(9)
memory usage: 7.3+ MB

In [ ]:

#Ejercicio crear una columna para clasificar a los jugadores por edad usando una funcion
 
#Ejemplo
# c) Formatear columnas existentes (ejemplos)
# Formatear la columna 'Value' para que sea numérica (eliminando '€' y 'M/K')
def format_currency(value):
    if isinstance(value, str):
        value = value.replace('€', '')
        if 'M' in value:
            return float(value.replace('M', '')) * 1000000
        elif 'K' in value:
            return float(value.replace('K', '')) * 1000
    return np.nan

df_cleaned['Value_Numeric'] = df_cleaned['Value'].apply(format_currency)
print("\nPrimeras filas con la columna 'Value_Numeric':")
print(df_cleaned[['Name', 'Value', 'Value_Numeric']].head())

In [ ]:
#Hasta aca se supone que ya tengo los datos preparados

In [19]:

# ------------------------------------------------------------------------------
# 4. Consultas en Pandas con Filtros
# ------------------------------------------------------------------------------

print("\n# 4. Consultas en Pandas con Filtros")

# a) Filtros básicos
print("\n# a) Filtros básicos")

#usando mascaras

#mask = (df_cleaned['age'] > 20 and df_cleaned['age'] < 30) and df_cleaned['nationality'] == 'France'

#df_cleaned[mask]
#older_players = df_cleaned[mask]
#older_players = older_players[['name', 'age', 'birth_date']]
df_cleaned[(df_cleaned['age'] > 20)&
           (df_cleaned['age'] < 30)&
           (df_cleaned['nationality'] == 'France')]

#Investigar y estudiar sobre logica booleana

# 4. Consultas en Pandas con Filtros

# a) Filtros básicos

,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,potential,...,interceptions,positioning,vision,penalties,composure,marking,standing_tackle,sliding_tackle,height_m,BMI
2,P. Pogba,Paul Pogba,3/15/1993,25,190.50,83.9,"CM,CAM",France,88,91,...,64,82,88,82,87,63,67,67,1.90,23.240997
13,A. Griezmann,Antoine Griezmann,3/21/1991,27,175.26,73.0,"CF,ST",France,89,90,...,49,91,85,83,89,59,54,48,1.75,23.836735
35,A. Martial,Anthony Martial,12/5/1995,23,182.88,76.2,"LW,ST,LM",France,84,90,...,42,83,74,81,82,34,39,36,1.83,22.753740
41,N. Fekir,Nabil Fekir,7/18/1993,25,172.72,74.8,CAM,France,84,88,...,28,81,81,76,89,31,37,25,1.73,24.992482
44,O. Dembélé,Ousmane Dembélé,5/15/1997,21,152.40,67.1,"RW,LW",France,84,92,...,36,79,84,75,82,42,30,33,1.52,29.042590
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17889,A. Lacazette,Alexandre Lacazette,5/28/1991,27,175.26,73.0,ST,France,85,86,...,42,86,76,84,85,29,42,30,1.75,23.836735
17898,A. Laporte,Aymeric Laporte,5/27/1994,24,187.96,84.8,"CB,LB",France,85,88,...,86,54,59,44,80,87,88,88,1.88,23.992757
17909,R. Varane,Raphaël Varane,4/25/1993,25,190.50,81.2,CB,France,86,91,...,82,44,56,43,84,87,88,87,1.90,22.493075
17917,S. Umtiti,Samuel Umtiti,11/14/1993,25,182.88,74.8,CB,France,87,92,...,87,58,58,61,82,90,89,86,1.83,22.335692
17929,N. Kanté,N'Golo Kanté,3/29/1991,27,167.64,72.1,"CDM,CM",France,89,90,...,92,71,80,54,85,90,91,85,1.68,25.545635

In [20]:
df_cleaned.nationality.unique()
#Para saber los valores unicos de un campo en particular

array(['Argentina', 'Denmark', 'France', 'Italy', 'Senegal',
       'Netherlands', 'Germany', 'Uruguay', 'Spain', 'Belgium', 'Egypt',
       'Slovakia', 'Brazil', 'Croatia', 'Costa Rica', 'Colombia',
       'Morocco', 'Portugal', 'Sweden', 'Bosnia Herzegovina', 'Mexico',
       'England', 'Austria', 'Iceland', 'Hungary', 'Wales', 'Ukraine',
       'Central African Rep.', 'Serbia', 'Ivory Coast', 'Cameroon',
       'Paraguay', 'Australia', 'Algeria', 'Romania', 'Russia', 'Israel',
       'Switzerland', 'Chile', 'Tunisia', 'Turkey', 'Nigeria', 'Peru',
       'Norway', 'Greece', 'United States', 'Venezuela', 'Iran',
       'Equatorial Guinea', 'Cape Verde', 'Tanzania', 'Scotland',
       'China PR', 'Kosovo', 'Montenegro', 'Canada', 'Madagascar', 'Mali',
       'Ghana', 'Guinea', 'Poland', 'Cuba', 'Northern Ireland', 'Japan',
       'New Zealand', 'Republic of Ireland', 'Ecuador', 'Burkina Faso',
       'Czech Republic', 'Slovenia', 'Belarus', 'Gabon', 'FYR Macedonia',
       'Curacao', 'DR Congo', 'Honduras', 'Sierra Leone', 'Guinea Bissau',
       'Saudi Arabia', 'Fiji', 'Korea Republic', 'Zambia', 'Syria',
       'Armenia', 'Georgia', 'Angola', 'South Africa', 'Zimbabwe',
       'Congo', 'Eritrea', 'Iraq', 'Albania', 'Gambia', 'Jamaica',
       'Burundi', 'Uganda', 'Benin', 'Suriname', 'Finland', 'Lithuania',
       'Togo', 'El Salvador', 'Korea DPR', 'Panama', 'Moldova', 'Haiti',
       'Comoros', 'Azerbaijan', 'Trinidad & Tobago', 'Liberia', 'Kenya',
       'Chad', 'Faroe Islands', 'Kazakhstan', 'Estonia', 'Bulgaria',
       'Montserrat', 'Dominican Republic', 'Thailand', 'Andorra', 'Sudan',
       'Hong Kong', 'Malta', 'Afghanistan', 'Uzbekistan', 'Palestine',
       'Yemen', 'Luxembourg', 'Mauritania', 'Indonesia', 'Bermuda',
       'Grenada', 'Philippines', 'Liechtenstein', 'Guyana',
       'St Kitts Nevis', 'Antigua & Barbuda', 'Cyprus', 'Rwanda',
       'South Sudan', 'Papua New Guinea', 'Latvia', 'Vietnam',
       'Nicaragua', 'Ethiopia', 'Barbados', 'Jordan', 'St Lucia',
       'Guatemala', 'Namibia', 'Guam', 'Bolivia', 'Mozambique', 'Kuwait',
       'Libya', 'New Caledonia', 'Oman', 'São Tomé & Príncipe',
       'United Arab Emirates'], dtype=object)

In [ ]:
older_players.to_csv('/home/ravi/Documents/Kevin/projects/data/viejos.csv', sep=';', index=False)
#para guardar los resultados en formato csv

In [ ]:
df_cleaned.age

In [22]:
#Algunas consultas en pandas

# Jugadores mayores de 30 años
older_players = df_cleaned[df_cleaned['age'] > 30]
print("\nJugadores mayores de 30 años (primeras 5):")
print(older_players.head())

Jugadores mayores de 30 años (primeras 5):
           name                       full_name  birth_date  age  height_cm  \
0      L. Messi  Lionel Andrés Messi Cuccittini   6/24/1987   31     170.18
8      M. Neuer                    Manuel Neuer   3/27/1986   32     193.04
9     E. Cavani    Edinson Roberto Cavani Gómez   2/14/1987   32     185.42
17  Fernandinho              Fernando Luiz Rosa    5/4/1985   33     152.40
18   G. Higuaín         Gonzalo Gerardo Higuaín  12/10/1987   31     185.42

    weight_kgs positions nationality  overall_rating  potential  ...  \
0         72.1  CF,RW,ST   Argentina              94         94  ...
8         92.1        GK     Germany              89         89  ...
9         77.1        ST     Uruguay              89         89  ...
17        67.1       CDM      Brazil              87         87  ...
18        88.9        ST   Argentina              87         87  ...

    interceptions  positioning vision  penalties  composure  marking  \
0              22           94     94         75         96       33
8              30           12     70         47         70       17
9              48           93     77         85         82       52
17             89           70     75         61         79       87
18             20           92     74         70         86       35

   standing_tackle  sliding_tackle height_m        BMI
0               28              26     1.70  24.948097
8               10              11     1.93  24.725496
9               45              39     1.85  22.527392
17              86              80     1.52  29.042590
18              22              18     1.85  25.975164

[5 rows x 53 columns]

In [25]:
df_cleaned.columns

Index(['name', 'full_name', 'birth_date', 'age', 'height_cm', 'weight_kgs',
       'positions', 'nationality', 'overall_rating', 'potential', 'value_euro',
       'wage_euro', 'preferred_foot', 'international_reputation(1-5)',
       'weak_foot(1-5)', 'skill_moves(1-5)', 'body_type',
       'release_clause_euro', 'national_team', 'national_rating',
       'national_team_position', 'national_jersey_number', 'crossing',
       'finishing', 'heading_accuracy', 'short_passing', 'volleys',
       'dribbling', 'curve', 'freekick_accuracy', 'long_passing',
       'ball_control', 'acceleration', 'sprint_speed', 'agility', 'reactions',
       'balance', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots',
       'aggression', 'interceptions', 'positioning', 'vision', 'penalties',
       'composure', 'marking', 'standing_tackle', 'sliding_tackle', 'height_m',
       'BMI'],
      dtype='object')

In [ ]:
# Jugadores que juegan en una posición específica (ej: ST - Striker)
strikers = df_cleaned[df_cleaned['positions'] == 'ST']
#Para comparar si una variable es igual a otra variable o a un valor se usa ==
#Para almacenar en una variable se usa =
print("\nJugadores que juegan como delanteros (primeras 5):")
print(strikers[['name', 
                'overall_rating', 
                'age']]
                .head()
                .drop_duplicates())
#Para ordenar el codigo, se puede hacer cuando hay comas o parentesis
print("el jugador esta 'viejo'")
#las comillas se usan de manera indiferente excepto en este caso

Jugadores que juegan como delanteros (primeras 5):
           name  overall_rating  age
7     S. Agüero              89   30
9     E. Cavani              89   32
18   G. Higuaín              87   31
26  C. Immobile              87   29
31    M. Icardi              87   26
el jugador esta 'viejo'

In [ ]:
# Jugadores con un potencial mayor a 85
high_potential = df_cleaned[df_cleaned['Potential'] > 85]
print("\nJugadores con potencial mayor a 85 (primeras 5):")
print(high_potential.head())

In [ ]:
#and: &, or: |
#Filtros complejos
df_kevin = df_cleaned[  ((df_cleaned['age']>=30)&(df_cleaned['nationality']=='France'))|
                        ((df_cleaned['age']<30)&(df_cleaned['nationality']=='England'))
           ]

In [ ]:
#Asi puedo validar
df_kevin[df_kevin.nationality=='England'].age.unique()
#otra variante
df_kevin[df_kevin['nationality']=='England']['age'].unique()
#por pasos
df1 = df_kevin[df_kevin.nationality=='England']#filtro por valor
df2 = df1['age']#filtro campos
df2.unique()#valores unicos

array([28, 25, 27, 23, 24, 29, 21, 18, 22, 26, 20, 19, 17])

In [ ]:
# Estudiar Lógica Matematica y booleana, conjuntos
# b) Filtros con múltiples condiciones (AND y OR)
#Operadores ==, >, <, >=, <=


print("\n# b) Filtros con múltiples condiciones (AND y OR)")

# Jugadores mayores de 30 años Y con un potencial mayor a 80
experienced_high_potential = df_cleaned[(df_cleaned['Age'] > 30) & (df_cleaned['Potential'] > 80)]
print("\nJugadores mayores de 30 años y con potencial mayor a 80 (primeras 5):")
print(experienced_high_potential.head())

# Jugadores que juegan como delanteros (ST) O mediocampistas centrales (CM)
attack_midfielders = df_cleaned[(df_cleaned['Position'] == 'ST') | (df_cleaned['Position'] == 'CM')]
print("\nJugadores que son delanteros o mediocampistas centrales (primeras 5):")
print(attack_midfielders.head())

#Ejercicio: Ejecutar este bloque y pensar en mas de un operador

In [ ]:
# c) Filtros con la función .isin() 
print("\n# c) Filtros con la función .isin()")

# Jugadores que juegan en ciertas posiciones específicas
#forma larga
defenders = df_cleaned[( (df_cleaned.positions=='GK')|
                       (df_cleaned.positions=='CB')|
                       (df_cleaned.positions=='LB')|
                       (df_cleaned.positions=='RB') )&
                       (df_cleaned.age<30)]
#forma corta
#hago una lista de las posiciones que me interesan
positions_of_interest = ['GK', 'CB', 'LB', 'RB']
#verifico que la posicion de los jugadores este en esa lista

defenders = df_cleaned[(df_cleaned['Position'].isin(positions_of_interest))&
                        (df_cleaned.age<30)]
print("\nJugadores que son defensas (porteros, centrales o laterales) y jovenes (primeras 5):")
print(defenders.head())

In [ ]:
# Ejercicios
# Jugadores de ciertos clubes
clubs_of_interest = ['FC Barcelona', 'Real Madrid', 'Manchester City']
players_in_top_clubs = df_cleaned[df_cleaned['Club'].isin(clubs_of_interest)]
print("\nJugadores de FC Barcelona, Real Madrid o Manchester City (primeras 5):")
print(players_in_top_clubs.head())

In [ ]:
#github.com trabajo colaborativo, control de versiones, CI/CD
#draw.io
# d) Filtros con la función .str.contains()
print("\n# d) Filtros con la función .str.contains()")

# Jugadores cuyo nombre contiene "Silva"
silva_players = df_cleaned[df_cleaned['full_name'].str.contains('Silva', case=False)]
#case = False es para que no diferencie mayusculas o minusculas
print("\nJugadores cuyo nombre contiene 'Silva' (ignorando mayúsculas/minúsculas) (primeras 5):")
print(silva_players.full_name.head())
# e) Filtros con la funcion startswith()
df_cleaned[df_cleaned.full_name.str.startswith('Marc')].full_name

# d) Filtros con la función .str.contains()

Jugadores cuyo nombre contiene 'Silva' (ignorando mayúsculas/minúsculas) (primeras 5):
22        Marcelo Vieira da Silva Júnior
51             William Silva de Carvalho
68       Malcom Filipe Silva de Oliveira
115        André Miguel Valente da Silva
165    Otávio Edmilson da Silva Monteiro
Name: full_name, dtype: object

12                Marc-André ter Stegen
22       Marcelo Vieira da Silva Júnior
43              Marco Asensio Willemsen
79                         Marco Parolo
101                     Marcel Sabitzer
                      ...
17806             Marcos Alonso Mendoza
17838                   Marcus Rashford
17895               Marcos  Aoás Corrêa
17908                    Marco Verratti
17926                        Marco Reus
Name: full_name, Length: 231, dtype: object

In [ ]:


# e) Definición de funciones para filtros más complejos
print("\n# e) Definición de funciones para filtros más complejos")

# Función para filtrar jugadores por un rango de edad y un potencial mínimo
def filter_by_age_potential(df, min_age, max_age, min_potential):
    filtered_df = df[(df['Age'] >= min_age) & (df['Age'] <= max_age) & (df['Potential'] >= min_potential)]
    return filtered_df

experienced_talents = filter_by_age_potential(df_cleaned, 25, 32, 82)
print("\nJugadores entre 25 y 32 años con un potencial mínimo de 82 (primeras 5):")
print(experienced_talents.head())

# Función para encontrar jugadores de una liga específica con un valor superior a un umbral
def filter_by_league_and_value(df, league, min_value):
    filtered_df = df[(df['League'] == league) & (df['Value_Numeric'] >= min_value)]
    return filtered_df

laliga_expensive_players = filter_by_league_and_value(df_cleaned, 'Spanish La Liga', 50000000)
print("\nJugadores de la Liga Española con un valor superior a 50 millones (primeras 5):")
print(laliga_expensive_players.head())

# ------------------------------------------------------------------------------
# 5. Ejercicios Prácticos
# ------------------------------------------------------------------------------

print("\n# 5. Ejercicios Prácticos")

print("\nEjercicio 1:")
print("Encuentra a todos los jugadores que juegan como porteros (GK) y tienen una valoración (Overall) superior a 80.")

print("\nEjercicio 2:")
print("¿Cuántos jugadores pertenecen al club 'Chelsea' y tienen una edad inferior a 25 años?")

print("\nEjercicio 3:")
print("Crea una función que reciba un dataframe y un valor de potencial mínimo, y devuelva los nombres de los jugadores con ese potencial o superior.")

print("\nEjercicio 4:")
print("Encuentra a los jugadores cuya altura esté entre 180 cm y 190 cm (inclusive) y cuyo peso esté entre 75 kg y 85 kg (inclusive). Muestra solo su nombre, altura y peso.")

print("\nEjercicio 5:")
print("¿Cuál es el promedio del 'Overall' para los jugadores de cada una de las ligas ('League')?")

print("\n¡Intenta resolver estos ejercicios utilizando los conocimientos que hemos cubierto! Puedes añadir más celdas de código debajo para tus soluciones.")